---
- hosts: all
  gather_facts: True
  become: true
  handlers:
    - name: Amazon Linux 1 Handlers
      import_tasks: OS/amazon1-handlers.yml
      when: ansible_distribution == "Amazon" and ansible_distribution_version != '2'
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]
    - name: Amazon Linux 1
      include_tasks: OS/amazon1-setup.yml
      when: ansible_distribution == "Amazon" and ansible_distribution_version != '2'
    - name: Amazon Linux 2
      include_tasks: OS/amazon2-setup.yml
      when: ansible_distribution == "Amazon" and ansible_distribution_version == '2'
    - name: RHEL7
      include_tasks: OS/rhel7-setup.yml
      when: (ansible_distribution == "RedHat" or ansible_distribution == "Red Hat Enterprise Linux") and ansible_distribution_version == '7'
