---
- hosts: all
  gather_facts: True
  tasks:
    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]
    - name: Amazon Linux 1
      include_tasks: OS/amazon1-setup.yml
      when: ansible_distribution == "Amazon" and ansible_distribution_version != '2'
    - name: Amazon Linux 2
      include_tasks: OS/amazon2-setup.yml
      when: ansible_distribution == "Amazon" and ansible_distribution_version == '2'

#- import_playbook: OS/amazon1-setup.yml
#  when: ansible_distribution == "Amazon" and ansible_distribution_version == '1'
#- import_playbook: OS/amazon2-setup.yml
#  when: ansible_distribution == "Amazon" and ansible_distribution_version == '2'

